// Generated by CoffeeScript 1.9.0
exports.capitalize = function(string) {
  return string[0].toUpperCase() + string.slice(1);
};

exports.getRandomInt = function(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
