// Generated by CoffeeScript 1.9.0
var Stimulus;

Stimulus = (function() {
  function Stimulus(params) {
    this._text = params._text;
    this.intent = params.intent;
    this.entities = params.entities;
    this.confidence = params.confidence;
  }

  return Stimulus;

})();

module["export"] = Stimulus;
