// Generated by CoffeeScript 1.9.1
var CLI, colors, readline;

readline = require('readline');

colors = require('colors');

CLI = (function() {
  function CLI(core, params) {
    this.core = core;
    this.params = params;
    this.core.brain.on('output', (function(_this) {
      return function(output) {
        if (output.text) {
          _this.print(output.text);
        }
        if (output.voice) {
          return _this.say(output.voice);
        }
      };
    })(this));
    this.rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    this.rl.on('line', (function(_this) {
      return function(line) {
        _this.core.brain.emit('input', line);
        return _this.rl.prompt(true);
      };
    })(this));
    this.rl.setPrompt('Igor: '.green);
    this.rl.prompt(true);
  }

  CLI.prototype.say = function(data) {
    return this.core.speech.exec(data);
  };

  CLI.prototype.print = function(data) {
    process.stdout.clearLine();
    process.stdout.cursorTo(0);
    console.log('Eve: '.magenta + data);
    return this.rl.prompt(true);
  };

  return CLI;

})();

module.exports = CLI;
