// Generated by CoffeeScript 1.9.0
var Q, Reflex;

Q = require('q');

Reflex = (function() {
  function Reflex(_at_stimulus) {
    this.stimulus = _at_stimulus;
  }

  Reflex.prototype.exec = function() {
    var Action, action, deferred, e;
    deferred = Q.defer();
    try {
      Action = require('../../modules/' + this.stimulus.intent);
    } catch (_error) {
      e = _error;
      console.log(e);
      deferred.reject(e);
    }
    action = new Action(this.stimulus.entities);
    action.exec().then(deferred.resolve);
    return deferred.promise;
  };

  return Reflex;

})();

module["export"] = Reflex;
