// Generated by CoffeeScript 1.9.1
var Ivona, Q, child, ivona;

Ivona = require('ivona-node');

child = require('child_process');

Q = require('q');

ivona = new Ivona({
  accessKey: 'GDNAI76SALPR4SUR7M2Q',
  secretKey: 'T7KnJwnw80hC+nhrTpDxdts5gC2dtiSeuTBP4fUp'
});

module.exports = {
  exec: function(phrase) {
    var sox;
    sox = child.spawn('sox', ['-t', 'mp3', '-', '-d', '-q']);
    return ivona.createVoice(phrase).pipe(sox.stdin);
  }
};
